name: Basic checks

on:
  push:
    branches: 
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    name: Install package and run tests
    runs-on: ubuntu-latest

    strategy:
        matrix:
          python-version:
            - "3.10"
    steps:
    - name: Check out the repo content
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install the package
      run: |
        python -m pip install --upgrade pip
        pip install .[test]

    - name: Run tests
      run: |
        pytest tests
